name: Build luci-app-filetransfer APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add dirs
        run: mkdir -p artifacts feed

      - name: Build
        uses: ./
        env:
          TARGET: airoha/an7581
          VERSION: master
          ARCH: aarch64_cortex-a53
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feed
          PACKAGES: luci-app-filetransfer
